### ISSUE TITLE
Fix the information in the data section

### ISSUE THREAD

**Issue by dvladek** [uuinfolab/uuinfolab.github.io#6]
The data page contains a lot of datasets that are not ours... should we be more transparent and add only ours or subdivide in two sections? I expected only to list datasets that are collected and maintained by us, not other useful data shared by other groups.

**Comment by magnanim** [comment]
I have removed the links to the four datasets that we did not collect, so I close this. We'll have to re-organise the data logic though, as now this is not FAIR.
